package com.redhat.gss;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;
	private int age;
	private java.lang.Boolean isAdult;

	public Person() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public int getAge() {
		return this.age;
	}

	public void setAge(int age) {
		this.age = age;
	}

	public java.lang.Boolean getIsAdult() {
		return this.isAdult;
	}

	public void setIsAdult(java.lang.Boolean isAdult) {
		this.isAdult = isAdult;
	}

	public Person(java.lang.String name, int age, java.lang.Boolean isAdult) {
		this.name = name;
		this.age = age;
		this.isAdult = isAdult;
	}

}